ALTER TABLE "AGREEMENT_SERVICE" ADD FOREIGN KEY ("AGREEMENT_ID") REFERENCES "AGREEMENT" ("ID");

ALTER TABLE "AGREEMENT_SERVICE" ADD FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("ID");

ALTER TABLE "SERVICE" ADD FOREIGN KEY ("BUILDING_ID") REFERENCES "BUILDING" ("ID");

ALTER TABLE "USER_AGREEMENT" ADD FOREIGN KEY ("AGREEMENT_ID") REFERENCES "AGREEMENT" ("ID");

ALTER TABLE "USER_AGREEMENT" ADD FOREIGN KEY ("SUBSCRIBER_ID") REFERENCES "SUBSCRIBER" ("ID");

ALTER TABLE "AGREEMENT" ADD FOREIGN KEY ("APARTMENT_ID") REFERENCES "APARTMENT" ("ID");

ALTER TABLE "AGREEMENT_DOC" ADD FOREIGN KEY ("AGREEMENT_ID") REFERENCES "AGREEMENT" ("ID");

ALTER TABLE "INVOICE" ADD FOREIGN KEY ("SUBSCRIBER_ID") REFERENCES "SUBSCRIBER" ("ID");

ALTER TABLE "INVOICE" ADD FOREIGN KEY ("TYPE_ID") REFERENCES "INVOICE_TYPE" ("ID");

ALTER TABLE "INVOICE" ADD FOREIGN KEY ("SERVICE_ID") REFERENCES "SERVICE" ("ID");

ALTER TABLE "EMPLOYEE" ADD FOREIGN KEY ("ROLE_ID") REFERENCES "EMPLOYEE_ROLE" ("Id");

ALTER TABLE "EMPLOYEE" ADD FOREIGN KEY ("USER_ID") REFERENCES "USER" ("Id");

ALTER TABLE "SUBSCRIBER" ADD FOREIGN KEY ("USER_ID") REFERENCES "USER" ("Id");

ALTER TABLE "EMPLOYEE" ADD FOREIGN KEY ("COMPANY_ID") REFERENCES "MANAGEMENT_COMPANY" ("ID");

ALTER TABLE "APARTMENT" ADD FOREIGN KEY ("BUILDING_ID") REFERENCES "BUILDING" ("ID");

ALTER TABLE "BUILDING" ADD FOREIGN KEY ("COMPANY_ID") REFERENCES "MANAGEMENT_COMPANY" ("ID");