CREATE SEQUENCE "customer" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "courier" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "package" MINVALUE 1 INCREMENT BY 1;
CREATE SEQUENCE "payment" MINVALUE 1 INCREMENT BY 1;
