CREATE OR REPLACE FUNCTION CUSTOMER_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"customer_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION COURIER_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"courier_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTIONPACKAGE_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"package_seq"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION PAYMENT_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."id":=NEXTVAL('"payment_seq");
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;
