version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.04.2
    parameters:
      app-name:
        type: string
    steps:
      - checkout
      - run: docker build -t $REGISTRY_HOST/<< parameters.app-name >> .
      - run: docker push $REGISTRY_HOST/<< parameters.app-name >>
  deploy:
    machine:
      image: ubuntu-2204:2022.04.2
    parameters:
      app-name:
        type: string
    steps:
      - run: ssh $DIGITALOCEAN_SSH_USER@$DIGITALOCEAN_SSH_HOST 'docker stop "'<< parameters.app-name >>'" | true; docker rm "'<< parameters.app-name >>'" | true; docker login --username="'$REGISTRY_USER'" --password="'$REGISTRY_PWD'" "'$REGISTRY_HOST'" && docker pull "'$REGISTRY_HOST'"/"'<< parameters.app-name >>'" && docker run -d --network=billkill-bridge --name "'<< parameters.app-name >>'" "'$REGISTRY_HOST'"/"'<< parameters.app-name >>'" && docker image prune -f'

workflows:
  deploy-test:
    when:
      equal: [ test, << pipeline.git.branch >> ]
    jobs:
      - build:
          context:
            - image-registry
          app-name: $APP_NAME_TEST
      - deploy:
          context:
            - digitalocean
            - image-registry
          requires:
            - build
          app-name: $APP_NAME_TEST
  # deploy-prod:
  #   when:
  #     equal: [ master, << pipeline.git.branch >> ]
  #   jobs:
  #     - build:
  #         app-name: $APP_NAME
  #     - deploy:
  #         requires:
  #           - build
  #         app-name: $APP_NAME
