CREATE SEQUENCE "AGREEMENT_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "AGREEMENT_DOC_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "AGREEMENT_SERVICE_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "USER_AGREEMENT_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "SERVICE_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "BUILDING_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "SUBSCRIBER_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "APARTMENT_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "INVOICE_TYPE_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "INVOICE_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "EMPLOYEE_ROLE_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "EMPLOYEE_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "USER_SEQ" MINVALUE 1 INCREMENT BY 1;

CREATE SEQUENCE "MANAGEMENT_COMPANY_SEQ" MINVALUE 1 INCREMENT BY 1;