CREATE OR REPLACE FUNCTION MANAGEMENT_COMPANY_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"MANAGEMENT_COMPANY_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION BUILDING_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"BUILDING_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION APARTMENT_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"APARTMENT_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION EMPLOYEE_ROLE_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"EMPLOYEE_ROLE_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION EMPLOYEE_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"EMPLOYEE_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION SUBSCRIBER_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"SUBSCRIBER_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION USER_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."Id":=NEXTVAL('"USER_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION INVOICE_TYPE_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"INVOICE_TYPE_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION INVOICE_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"INVOICE_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION AGREEMENT_DOC_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"AGREEMENT_DOC_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION AGREEMENT_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"AGREEMENT_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION USER_AGREEMENT_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"USER_AGREEMENT_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION SERVICE_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"SERVICE_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;

 CREATE OR REPLACE FUNCTION AGREEMENT_SERVICE_TG_FUNC() RETURNS "trigger" AS $BODY$
 BEGIN
   NEW."ID":=NEXTVAL('"AGREEMENT_SERVICE_SEQ"');
   RETURN NEW;
 END;
 $BODY$ LANGUAGE 'plpgsql' VOLATILE;
